chore: updated the repl gh action

diff --git a/.github/actions/repl/action.yml b/.github/actions/repl/action.yml
--- a/.github/actions/repl/action.yml
+++ b/.github/actions/repl/action.yml
@@ -15,4 +15,4 @@ runs:
         bin/pact -t ${{ inputs.target }} > out.log 2>&1
         cat out.log
         r=`tail -1 out.log | grep "Load successful"`
-        if [ -n "$r" ]; then exit 0; else cat out.log; echo "Pact run failed."; exit 1; fi
+        if [ -n "$r" ]; then exit 0; else cat out.log; echo "\nPact run failed."; exit 1; fi
