Including dutch auction in CI

diff --git a/.github/workflows/pact.yml b/.github/workflows/pact.yml
--- a/.github/workflows/pact.yml
+++ b/.github/workflows/pact.yml
@@ -87,3 +87,10 @@ jobs:
           cat out.log
           r=`tail -1 out.log | grep "Load successful"`
           if [ -n "$r" ]; then exit 0; else echo "Pact run failed."; exit 1; fi
+
+      - name: Test dutch auction sale contract
+        run: |
+          bin/pact -t pact/sale-contracts/dutch-auction/dutch-auction.repl > out.log 2>&1
+          cat out.log
+          r=`tail -1 out.log | grep "Load successful"`
+          if [ -n "$r" ]; then exit 0; else echo "Pact run failed."; exit 1; fi
