Add collection policy test

diff --git a/.github/workflows/pact.yml b/.github/workflows/pact.yml
--- a/.github/workflows/pact.yml
+++ b/.github/workflows/pact.yml
@@ -6,7 +6,7 @@ name: CI
 on:
   push:
     branches:
-      - v2-ci-test
+      - main
   pull_request:
 
   # Allows you to run this workflow manually from the Actions tab
@@ -44,3 +44,9 @@ jobs:
           cat out.log
           r=`tail -1 out.log | grep "Load successful"`
           if [ -n "$r" ]; then exit 0; else echo "Pact run failed."; exit 1; fi
+      - name: Test concrete collection-policy
+        run: |
+          bin/pact -t pact/concrete-policies/collection-policy/collection-policy-v1.repl > out.log 2>&1
+          cat out.log
+          r=`tail -1 out.log | grep "Load successful"`
+          if [ -n "$r" ]; then exit 0; else echo "Pact run failed."; exit 1; fi     
