Test execution

diff --git a/.github/workflows/pact.yml b/.github/workflows/pact.yml
--- a/.github/workflows/pact.yml
+++ b/.github/workflows/pact.yml
@@ -6,7 +6,7 @@ name: CI
 on:
   push:
     branches:
-      - main
+      - v2-ci-test
   pull_request:
 
   # Allows you to run this workflow manually from the Actions tab
@@ -41,6 +41,30 @@ jobs:
       - name: pact/marmalade.repl
         run: |
           bin/pact -t pact/marmalade.repl > out.log 2>&1
+          cat out.log
+          r=`tail -1 out.log | grep "Load successful"`
+          if [ -n "$r" ]; then exit 0; else echo "Pact run failed."; exit 1; fi
+      - name: Test concrete collection-policy
+        run: |
+          bin/pact -t pact/concrete-policies/collection-policy/collection-policy-v1.repl > out.log 2>&1
+          cat out.log
+          r=`tail -1 out.log | grep "Load successful"`
+          if [ -n "$r" ]; then exit 0; else echo "Pact run failed."; exit 1; fi
+      - name: Test concrete fungible-quote-policy
+        run: |
+          bin/pact -t pact/concrete-policies/fungible-quote-policy/fungible-quote-policy-v1.repl > out.log 2>&1
+          cat out.log
+          r=`tail -1 out.log | grep "Load successful"`
+          if [ -n "$r" ]; then exit 0; else echo "Pact run failed."; exit 1; fi
+      - name: Test concrete non-fungible-policy
+        run: |
+          bin/pact -t pact/concrete-policies/non-fungible-policy/non-fungible-policy-v1.repl > out.log 2>&1
+          cat out.log
+          r=`tail -1 out.log | grep "Load successful"`
+          if [ -n "$r" ]; then exit 0; else echo "Pact run failed."; exit 1; fi
+      - name: Test concrete royalty-policy
+        run: |
+          bin/pact -t pact/concrete-policies/royalty-policy/royalty-policy-v1.repl > out.log 2>&1
           cat out.log
           r=`tail -1 out.log | grep "Load successful"`
           if [ -n "$r" ]; then exit 0; else echo "Pact run failed."; exit 1; fi
